# Generated by Django 4.2.6 on 2023-11-20 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20, verbose_name="キャラクター")),
            ],
        ),
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20, verbose_name="マップ")),
            ],
        ),
        migrations.CreateModel(
            name="Lineups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="タイトル")),
                ("comment", models.TextField(verbose_name="説明")),
                ("image1", models.ImageField(upload_to="photos", verbose_name="イメージ１")),
                (
                    "image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos", verbose_name="イメージ２"
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos", verbose_name="イメージ３"
                    ),
                ),
                ("posted_at", models.DateField(auto_now_add=True, verbose_name="投稿日時")),
                (
                    "Character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="kouryaku.character",
                        verbose_name="キャラクター",
                    ),
                ),
                (
                    "Map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="kouryaku.map",
                        verbose_name="マップ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
        ),
    ]
